# Generated by Django 4.2.17 on 2025-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_duration_quiz_is_free_quiz_is_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
