# Generated by Django 4.2.17 on 2025-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_useranswer_options_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='taken_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
